meta:
  url:
  name: "CNCJ Workshop: The Kubernetes Playground"
  author: Harry Lee
  thumbnail:
  description:
  sns:
    - twitter
slide:
  loop: true
  sidebar: true
  targetBlank: true
  showIndex: false
  isVertical: false
  code:
    languages:
      - javascript
    plugins: []
    theme: default
extends:
  js:
  css:
