{{- if .Values.service.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "details.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "details.name" . }}
    helm.sh/chart: {{ include "details.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app: {{ include "details.name" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      name: http
  selector:
    app.kubernetes.io/name: {{ include "details.name" . }}
    app: {{ include "details.name" . }}
{{- end}}
